// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221228153021_mig_accussedones_changetablename")]
    partial class mig_accussedones_changetablename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedOne", b =>
                {
                    b.Property<int>("AccussedOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccussedOneClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedOneImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedOneNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccussedOneID");

                    b.ToTable("AccussedOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedTwo", b =>
                {
                    b.Property<int>("AccussedTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccussedTwoClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedTwoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedTwoNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccussedTwoID");

                    b.ToTable("AccussedTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DetectiveStory", b =>
                {
                    b.Property<int>("DetectiveStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetectiveDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetectiveStoryID");

                    b.ToTable("DetectiveStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FindKiller", b =>
                {
                    b.Property<int>("FindKillerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FindKillerClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FindKillerStatus")
                        .HasColumnType("bit");

                    b.HasKey("FindKillerID");

                    b.ToTable("FindKillers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Intro", b =>
                {
                    b.Property<int>("IntroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntroDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntroID");

                    b.ToTable("Intros");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationOne", b =>
                {
                    b.Property<int>("InvestigationOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvOneAnswer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneAnswer9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvOneChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("InvOneCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneClosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvOneDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvOneImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOnePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneQuestion9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationOneID");

                    b.ToTable("InvestigationsOne");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationTwo", b =>
                {
                    b.Property<int>("InvestigationTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvTwoAnswer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoAnswer9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvTwoChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("InvTwoCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoClosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvTwoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvTwoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoQuestion9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationTwoID");

                    b.ToTable("InvestigationsTwo");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneOne", b =>
                {
                    b.Property<int>("SceneOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneOneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneOneID");

                    b.ToTable("SceneOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneTwo", b =>
                {
                    b.Property<int>("SceneTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneTwoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneTwoID");

                    b.ToTable("SceneTwos");
                });
#pragma warning restore 612, 618
        }
    }
}
