// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221231010804_mig_foreignkeychange_InvAcs")]
    partial class mig_foreignkeychange_InvAcs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutValueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedOne", b =>
                {
                    b.Property<int>("AccussedOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccussedOneClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedOneImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedOneNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvestigationOneID")
                        .HasColumnType("int");

                    b.HasKey("AccussedOneID");

                    b.HasIndex("InvestigationOneID");

                    b.ToTable("AccussedOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedTwo", b =>
                {
                    b.Property<int>("AccussedTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccussedTwoClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedTwoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccussedTwoNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccussedTwoID");

                    b.ToTable("AccussedTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DetectiveStory", b =>
                {
                    b.Property<int>("DetectiveStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetectiveDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetectiveStoryID");

                    b.ToTable("DetectiveStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FindKiller", b =>
                {
                    b.Property<int>("FindKillerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FindKillerClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindKillerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FindKillerStatus")
                        .HasColumnType("bit");

                    b.HasKey("FindKillerID");

                    b.ToTable("FindKillers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Intro", b =>
                {
                    b.Property<int>("IntroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntroDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntroID");

                    b.ToTable("Intros");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationOne", b =>
                {
                    b.Property<int>("InvestigationOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvOneChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("InvOneCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneClosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvOneDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvOneImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOneOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvOnePhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationOneID");

                    b.ToTable("InvestigationOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationTwo", b =>
                {
                    b.Property<int>("InvestigationTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccussedTwoID")
                        .HasColumnType("int");

                    b.Property<int>("InvTwoChildrenNo")
                        .HasColumnType("int");

                    b.Property<string>("InvTwoCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoClosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvTwoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvTwoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoNameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvTwoPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationTwoID");

                    b.HasIndex("AccussedTwoID");

                    b.ToTable("InvestigationTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionOne", b =>
                {
                    b.Property<int>("QuestionOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvestigationOneID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionOneAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionOneQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionOneID");

                    b.HasIndex("InvestigationOneID");

                    b.ToTable("QuestionOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionTwo", b =>
                {
                    b.Property<int>("QuestionTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvestigationTwoID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTwoAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTwoQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionTwoID");

                    b.HasIndex("InvestigationTwoID");

                    b.ToTable("QuestionTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneOne", b =>
                {
                    b.Property<int>("SceneOneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneOneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneOneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneOneID");

                    b.ToTable("SceneOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SceneTwo", b =>
                {
                    b.Property<int>("SceneTwoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SceneTwoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneTwoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneTwoID");

                    b.ToTable("SceneTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedOne", b =>
                {
                    b.HasOne("EntityLayer.Concrete.InvestigationOne", "InvestigationOne")
                        .WithMany("AccussedOnes")
                        .HasForeignKey("InvestigationOneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationOne");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationTwo", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AccussedTwo", "AccussedTwo")
                        .WithMany("InvestigationTwos")
                        .HasForeignKey("AccussedTwoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccussedTwo");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionOne", b =>
                {
                    b.HasOne("EntityLayer.Concrete.InvestigationOne", "InvestigationOne")
                        .WithMany("QuestionOnes")
                        .HasForeignKey("InvestigationOneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationOne");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionTwo", b =>
                {
                    b.HasOne("EntityLayer.Concrete.InvestigationTwo", "InvestigationTwo")
                        .WithMany("QuestionTwos")
                        .HasForeignKey("InvestigationTwoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationTwo");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AccussedTwo", b =>
                {
                    b.Navigation("InvestigationTwos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationOne", b =>
                {
                    b.Navigation("AccussedOnes");

                    b.Navigation("QuestionOnes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.InvestigationTwo", b =>
                {
                    b.Navigation("QuestionTwos");
                });
#pragma warning restore 612, 618
        }
    }
}
